apiVersion: apps/v1
kind: Deployment
metadata:
  name: crash-loop-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crash-loop
  template:
    metadata:
      labels:
        app: crash-loop
    spec:
      containers:
      - name: crash-loop-container
        image: busybox
        command: ["/bin/sh", "-c", "echo 'Crashing...'; sleep 2; exit 1"]