apiVersion: v1
kind: Pod
metadata:
  name: pending-pod
  labels:
    app: pending-pod
    scenario: pending
spec:
  containers:
  - name: pending-container
    image: nginx:latest
    resources:
      requests:
        cpu: "100"
        memory: "100Gi"
  restartPolicy: Never